version: "3.8"
services:
  app:
    build: .
    command: foreman start
    ports:
      - "80:80"
    volumes:
      - .:/Sinatra-Docker
    links:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: redis
